project:
  type: book

filters:
  - abstract-section

book:
  title: "Human Activity Recognition with Consumer Devices and Real-Life Perspectives"
  favicon: figs/book.svg
  author: 
  - name: Miguel Matey Sanz
    orcid: 0000-0002-1189-5079
    email: matey@uji.es
    corresponding: true
    degrees:
      - MSc
    affiliation:
      - id: uji
        name: Universitat Jaume I
        city: Castellón de la Plana
        country: Spain
        url: www.uji.es
  - name: (Supervisor) Carlos Granell
    orcid: 0000-0003-1004-9695
    roles: supervision
    degrees:
      - PhD
    affiliation:
      - ref: uji
  - name: (Supervisor) Sven Casteleyn
    orcid: 0000-0003-0572-5716
    roles: supervision
    degrees:
      - PhD
    affiliation:
      - ref: uji
  date: now

  page-footer:
    left: |
      *Human Activity Recognition with Consumer Devices and Real-Life Perspectives* 
      <br>
      Licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) © Miguel Matey Sanz, 2024
    right: |
      This book was built with ❤️ and <a href="https://quarto.org/">Quarto</a>.
    background: light

  search: true
  repo-url: https://github.com/matey97/thesis
  repo-actions: [source]
  repo-link-target: blank

  sidebar:
    logo: figs/uji-logo.png
    border: true
  #  style: docked

  chapters:
    - href: index.qmd
      text: Preface
    - 01_intro.qmd
    - part: 02_materials-methods.qmd
      chapters:
        - 02.1_collection-tools.qmd
        - 02.2_dataset.ipynb
        - 02.3_methods.qmd
    - part: 03_analysis-har.qmd
      text: Multidimensional Analysis
      chapters:
        - 03.1_training-data.ipynb
        - 03.2_data-sources.ipynb
        - 03.3_models.ipynb
    - part: 04_tug.qmd
      text: "HAR in mHealth: TUG test"
      chapters:
        - 04.1_splitting-approach.ipynb
        - 04.2_system-reliability.ipynb
        - 04.3_energy-consumption.ipynb
    - part: 05_wifi-csi.qmd
      text: Wi-Fi CSI based HAR
      chapters:
        - 05.1_localized-har.ipynb
        - 05.2_methods-validation.ipynb
        - 05.3_csi-stability.ipynb
    - 06_conclusions.qmd
    - references.qmd
  appendices:
    - part: reference/index.qmd
      text: Reference
      chapters: 
        - reference/chapter2.data_loading.qmd
        - reference/chapter2.exploration.qmd
        - reference/chapter2.visualization.qmd
        - reference/chapter3.pipeline.01_data-processing.qmd
        - reference/chapter3.pipeline.02_hyperparameter-optimization.qmd
        - reference/chapter3.pipeline.03_incremental-loso.qmd
        - reference/chapter3.analysis.data_loading.qmd
        - reference/chapter3.analysis.model.qmd
        - reference/chapter3.analysis.statistical_tests.qmd
        - reference/chapter3.analysis.visualization.qmd
        - reference/chapter4.pipeline.01_relabel.qmd
        - reference/chapter4.pipeline.02_splitting-evaluation.qmd
        - reference/chapter4.analysis.data_loading.qmd
        - reference/chapter4.analysis.statistical_tests.qmd
        - reference/chapter4.analysis.tug_results_processing.qmd
        - reference/chapter4.analysis.visualization.qmd   
        - reference/chapter4.analysis.battery.qmd
        - reference/chapter5.pipeline.01_1_preliminar-dataset-processing.qmd
        - reference/chapter5.pipeline.01_2_stanwifi-processing.qmd
        - reference/chapter5.pipeline.01_3_multienvironment-processing.qmd
        - reference/chapter5.pipeline.01_4_lodo-dataset-processing.qmd
        - reference/chapter5.pipeline.02_hyperparameter-optimization.qmd
        - reference/chapter5.pipeline.03_1_multiple-evaluations.qmd
        - reference/chapter5.pipeline.03_2_cross-validation.qmd
        - reference/chapter5.pipeline.03_3_lodo.qmd
        - reference/chapter5.analysis.reports.qmd
        - reference/chapter5.analysis.visualization.qmd
    - tools.qmd

  license: "CC BY-NC-SA"
  
quartodoc:
  package: libs
  parser: google

  sections:
    - title: Chapter 2
      #package: libs.chapter2
      desc: "Defines the functions employed in the Chapter 2: Materials & Methods."
      contents:
        - chapter2.data_loading
        - chapter2.exploration
        - chapter2.visualization
    - title: Chapter 3
      #package: libs.chapter3
      desc: "Defines the functions employed in the Chapter 3: Multidimensional analysis of ML and DL on HAR."
    - subtitle: Pipeline
      desc: "Functions employed to carry out the experiments."
      contents:
        - chapter3.pipeline.01_data-processing
        - chapter3.pipeline.02_hyperparameter-optimization
        - chapter3.pipeline.03_incremental-loso
    - subtitle: Analysis
      desc: "Functions employed to analyse the results of the experiment."
      contents:
        - chapter3.analysis.data_loading
        - chapter3.analysis.model
        - chapter3.analysis.statistical_tests
        - chapter3.analysis.visualization
    - title: Chapter 4
      desc: "Defines the functions employed in the Chapter 4 - HAR in mHealth: TUG test using smartphones and smartwatches."
    - subtitle: Pipeline
      desc: "Functions employed to carry out the experiments."
      contents:
        - chapter4.pipeline.01_relabel
        - chapter4.pipeline.02_splitting-evaluation
    - subtitle: Analysis
      desc: "Functions employed to analyse the results of the experiments."
      contents:
        - chapter4.analysis.data_loading
        - chapter4.analysis.statistical_tests
        - chapter4.analysis.tug_results_processing
        - chapter4.analysis.visualization
        - chapter4.analysis.battery
    - title: Chapter 5
      desc: "Defines the functions employed in the Chapter 5 - Looking into the future: Wi-Fi CSI based HAR."
    - subtitle: Pipeline
      desc: "Functions employed to carry out the experiments."
      contents:
        - chapter5.pipeline.01_1_preliminar-dataset-processing
        - chapter5.pipeline.01_2_stanwifi-processing
        - chapter5.pipeline.01_3_multienvironment-processing
        - chapter5.pipeline.01_4_lodo-dataset-processing
        - chapter5.pipeline.02_hyperparameter-optimization
        - chapter5.pipeline.03_1_multiple-evaluations
        - chapter5.pipeline.03_2_cross-validation
        - chapter5.pipeline.03_3_lodo
    - subtitle: Analysis
      desc: "Functions employed to analyse the results of the experiments."
      contents:
        - chapter5.analysis.reports
        - chapter5.analysis.visualization


bibliography: references.bib

format:
  html:
    reference-location: margin
    execute:
      warning: false
    number-sections: false
    mainfont: "Roboto"
    monofont: "Roboto Mono"
    fontsize: "15px"
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css?family=Roboto:400,500,700" type="text/css"/>
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css?family=Roboto+Mono" type="text/css"/>
    theme:
      light: lumen
      dark: darkly
    code-fold: true
    toc-depth: 4
    #toc-expand: true
    smooth-scroll: true



