# chapter4.analysis.visualization { #libs.chapter4.analysis.visualization }

`chapter4.analysis.visualization`

Provides functions to visualize the obtained results.

## Functions

| Name | Description |
| --- | --- |
| [bland_altman_plot](#libs.chapter4.analysis.visualization.bland_altman_plot) | Generates a Bland-Altman plot to visualize the agreement of the measures generated by the system and the reference method. |
| [error_distribution](#libs.chapter4.analysis.visualization.error_distribution) | Generates a figure containing a box plot for each TUG measure and system configuration to show their distributions. |

### bland_altman_plot { #libs.chapter4.analysis.visualization.bland_altman_plot }

`chapter4.analysis.visualization.bland_altman_plot(system_results, man_results, system_desc, attrs, with_titles=True, limit_y_axis_to=None)`

Generates a Bland-Altman plot to visualize the agreement of the measures generated by the system and the reference method.

#### Parameters

| Name              | Type                  | Description                                                                       | Default    |
|-------------------|-----------------------|-----------------------------------------------------------------------------------|------------|
| `system_results`  | `pandas.DataFrame`    | DataFrame containing the system's generated measures.                             | _required_ |
| `man_results`     | `pandas.DataFrame`    | DataFrame containing the reference measures.                                      | _required_ |
| `system_desc`     | str                   | Label identifier for the system measures (e.g., C1, C2, etc.).                    | _required_ |
| `attrs`           | list\[str\]           | List containing the TUG measures to include in the plot as subplots.              | _required_ |
| `with_titles`     | bool                  | If `True`, include a title (i.e., measure's name) for each subplot.               | `True`     |
| `limit_y_axis_to` | list\[float\] \| None | If not `None`, the y axis of the plots will be limited to the specified interval. | `None`     |

#### Returns

| Type            | Description                |
|-----------------|----------------------------|
| `plotly.Figure` | Interactive Plotly figure. |

### error_distribution { #libs.chapter4.analysis.visualization.error_distribution }

`chapter4.analysis.visualization.error_distribution(errors_df)`

Generates a figure containing a box plot for each TUG measure and system configuration to show their distributions.
For each distribution, indicates if it is statistically different from 0 (i.e., no error) or not showing a p-value
of a statistical test below the box plot.

#### Parameters

| Name        | Type               | Description                                                                     | Default    |
|-------------|--------------------|---------------------------------------------------------------------------------|------------|
| `errors_df` | `pandas.DataFrame` | DataFrame containing the errors between the systema and the reference measures. | _required_ |

#### Returns

| Type            | Description                |
|-----------------|----------------------------|
| `plotly.Figure` | Interactive Plotly figure. |