# chapter5.analysis.visualization { #libs.chapter5.analysis.visualization }

`chapter5.analysis.visualization`

Provides functions to visualize the obtained results.

## Functions

| Name | Description |
| --- | --- |
| [plot_confusion_matrix](#libs.chapter5.analysis.visualization.plot_confusion_matrix) | Plots the confusion matrix resulting from the evaluation of a machine learning model. |

### plot_confusion_matrix { #libs.chapter5.analysis.visualization.plot_confusion_matrix }

`chapter5.analysis.visualization.plot_confusion_matrix(report, prediction_target, labels)`

Plots the confusion matrix resulting from the evaluation of a machine learning model.

#### Parameters

| Name                | Type        | Description                                                      | Default    |
|---------------------|-------------|------------------------------------------------------------------|------------|
| `report`            | dict        | Dict containing a classification report from a model evaluation. | _required_ |
| `prediction_target` | str         | String describing what is being classified.                      | _required_ |
| `labels`            | list\[str\] | List with the associated classes labels.                         | _required_ |

#### Returns

| Type            | Description                |
|-----------------|----------------------------|
| `plotly.Figure` | Interactive Plotly figure. |