# Function reference {.doc .doc-index}

## Chapter 2

Defines the functions employed in the Chapter 2: Materials & Methods.

| | |
| --- | --- |
| [chapter2.data_loading](chapter2.data_loading.qmd#libs.chapter2.data_loading) | Provides functions to load the collected data and associated metadata files. |
| [chapter2.exploration](chapter2.exploration.qmd#libs.chapter2.exploration) | Provides functions to compute statistics regarding subjects and collected data. |
| [chapter2.visualization](chapter2.visualization.qmd#libs.chapter2.visualization) | Provides a function to plot the collected data. |

## Chapter 3

Defines the functions employed in the Chapter 3: Multidimensional analysis of ML and DL on HAR.

### Pipeline

Functions employed to carry out the experiments.

| | |
| --- | --- |
| [chapter3.pipeline.01_data-processing](chapter3.pipeline.01_data-processing.qmd#libs.chapter3.pipeline.01_data-processing) | Data preprocessing script. |
| [chapter3.pipeline.02_hyperparameter-optimization](chapter3.pipeline.02_hyperparameter-optimization.qmd#libs.chapter3.pipeline.02_hyperparameter-optimization) | Hyperparameters Grid Search script. |
| [chapter3.pipeline.03_incremental-loso](chapter3.pipeline.03_incremental-loso.qmd#libs.chapter3.pipeline.03_incremental-loso) | Incremental Leaving-One-Subject-Out script. |

### Analysis

Functions employed to analyse the results of the experiment.

| | |
| --- | --- |
| [chapter3.analysis.data_loading](chapter3.analysis.data_loading.qmd#libs.chapter3.analysis.data_loading) | Provides functions to load the obtained results. |
| [chapter3.analysis.model](chapter3.analysis.model.qmd#libs.chapter3.analysis.model) | Defines a model to manage the reports generated by the machine and deep learning models. |
| [chapter3.analysis.statistical_tests](chapter3.analysis.statistical_tests.qmd#libs.chapter3.analysis.statistical_tests) | Provides functions to compute statistical tests to determine the significance of the obtained results. |
| [chapter3.analysis.visualization](chapter3.analysis.visualization.qmd#libs.chapter3.analysis.visualization) | Provides functions to visualize the obtained results. |

## Chapter 4

Defines the functions employed in the Chapter 4 - HAR in mHealth: TUG test using smartphones and smartwatches.

### Pipeline

Functions employed to carry out the experiments.

| | |
| --- | --- |
| [chapter4.pipeline.01_relabel](chapter4.pipeline.01_relabel.qmd#libs.chapter4.pipeline.01_relabel) | Data relabelling script. |
| [chapter4.pipeline.02_splitting-evaluation](chapter4.pipeline.02_splitting-evaluation.qmd#libs.chapter4.pipeline.02_splitting-evaluation) | Splitting approach evaluation script |

### Analysis

Functions employed to analyse the results of the experiments.

| | |
| --- | --- |
| [chapter4.analysis.data_loading](chapter4.analysis.data_loading.qmd#libs.chapter4.analysis.data_loading) | Provides functions to load the obtained results. |
| [chapter4.analysis.statistical_tests](chapter4.analysis.statistical_tests.qmd#libs.chapter4.analysis.statistical_tests) | Provides functions to compute statistical tests to determine the significance of the obtained results. |
| [chapter4.analysis.tug_results_processing](chapter4.analysis.tug_results_processing.qmd#libs.chapter4.analysis.tug_results_processing) | Provides functions to process the raw results of the TUG test obtained by the developed system and the reference method. |
| [chapter4.analysis.visualization](chapter4.analysis.visualization.qmd#libs.chapter4.analysis.visualization) | Provides functions to visualize the obtained results. |
| [chapter4.analysis.battery](chapter4.analysis.battery.qmd#libs.chapter4.analysis.battery) | Provides functions to process the battery consumption results |